# Generated by Django 4.1 on 2022-10-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('area', models.TextField(max_length=20)),
                ('member_number', models.IntegerField()),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('lobby_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='lobby.lobby')),
            ],
        ),
    ]
