# Generated by Django 4.1.1 on 2022-11-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='food_category',
            field=models.CharField(choices=[('bunsik', '분식'), ('korean', '한식'), ('western', '양식'), ('hambuger', '햄버거'), ('salad', '샐러드'), ('dessert', '디저트'), ('chicken', '치킨'), ('bread', '빵')], default='bunsik', max_length=20),
        ),
    ]
